### PR TITLE
Imprecise age

### PR DESCRIPTION
**Pull request by ielis**
Improve modeling of temporal elements and use the improved model across the `HpoDisease` and the associated classes.

### CODE REVIEW

**Comment by ielis** [comment]
Hi @pnrobinson @julesjacobsen @iimpulse ,
I'd like to make these changes to _Phenol_'s representation of temporal data and, consequently, the `HpoDisease` and `HpoDiseaseAnnotation` model classes. Please provide feedback during this week if you have a chance. If there is no input, I'll move forward & merge. However, please let me know if you can review but you'd need more time.

The PR involves two areas: the *temporal model* and the *disease model*

## Phenol temporal model

The temporal API consists of 5 interfaces `TemporalPoint`, `TemporalRange`, `Age`, `AgeRange`, and `TimelineAware`,  for putting concepts into the temporal axis. The picture presents the classes:
phenol_temporal

There are two _"timelines"_: *gestational* and *postnatal*. We must have these since we need to model the gestational age and we cannot arbitrarily assume that each pregnancy ends after 40 weeks of gestation. 

`TemporalPoint` is like a `Timestamp` and represents the number of days since start of the timeline. However, the start is not UNIX epoch (Jan 1 1970), but either the last menstrual period (LMB) or the birth. So, `TemporalPoint` is a timestamp of an event that happens on *gestational* or *postnatal* timeline. 

`TemporalRange` is a pair of `TemporalPoint`s: `start()` and `end()`. We avoid the coordinate system fuss; the `start()` is always *included* and `end()` is always *excluded*.

`Age` is a `TemporalPoint` with a `ConfidenceInterval`, hence possibly imprecise. `Age` also extends `TemporalRange`; here `start()` and `end()` represent the interval spanned by the `ConfidenceInterval`. The length of the `TemporalRange` is equal to zero for all precise `Age`s.

### Gotchas

There are a few places where I am not 100% sure if they'll work out. I am not sure if using `float` to represent the number of days is a good idea. The older version used `int`, however, the API was not nice because of situations like:

```java
Age oneYear = Age.of(1, 0, 0);           // create Age to represent 1 Julian year = 365.25 days
assertThat(oneYear.years(), equalTo(1)); // FAILS!
```
The assertion above fails. If we use `int` to store the number of days, the first line must round one year to 365 days. When calling the `years()` method, the code does the following:
```java
default float years() {
    return days() / Age.DAYS_IN_JULIAN_YEAR;
}
```
In result, `365 / 365.25 != 1` the assertion fails, and the WTF factor skyrockets. The example above works OK if we use `float` instead of `int`, and we can get `weeks()`, `months()` and `years()` from any `TemporalPoint`.

*Please let me know if you think it is a bad idea to use `float` in this context.*

## Phenol disease model

I went through the `HpoDiseaseAnnotation` and `HpoDisease` to clean the code and to write better documentation. However, I also propose removing the `HpoDiseaseAnnotationMetadata` from `HpoDiseaseAnnotation`. Here, `HpoDiseaseAnnotation` is an aggregation of a phenotypic feature based on one or more patients, and  `HpoDiseaseAnnotationMetadata` represents the individual data points that provide onset, frequency, modifiers, and sex observed in the cohort members. Previously, `HpoDiseaseAnnotation` included
```java
Stream<HpoDiseaseAnnotationMetadata> metadata();
```
However, it does not fit into the interface for me anymore, looks more like an implementation detail and a promise that is too strong. We can use metadata to implement the `HpoDiseaseAnnotation` methods but we should not include it in the API.

----
So these are the 2 change areas. Please let me know if you have any comments.
Thanks & cheers!

**Comment by pnrobinson** [comment]
@ielis I am not convinced that having this level of resolution is good. Because if we get the information that a patient is "one year old" this is a fuzzy concept where there is no difference between 364 and 365 days. On the other hand, I think people do regard day as an integer concept in almost all contexts. Let's discuss this!

**Comment by ielis** [comment]
@pnrobinson @julesjacobsen I reverted to using `int` for numbering of days. With this change, the API feels more natural and looks better.

I also made one additional change in the conversion of months to days; the function rounds up instead of flooring the number of days obtained from months and years. If we floor the number of days, the following will fail:

```java
Age age = Age.postnatal(1, 0, 0);
assertThat(age.completeYears(), equalTo(1));
```
This is because `age` has 365 days that is less than `365.25` of the Julian year. However, if we round up, the The conversion was already imperfect, introducing error of 1 day in the worst case. The error magnitude stays the same with rounding up, so we're where we were before.

The `TemporalPoint`'s API now offers `int completeYears()`, `int completeMonths()`, and `int completeWeeks()`.

I renamed `ConfidenceInterval` to `ConfidenceRange`. The Javadoc in `ConfidenceRange` states that the class should *not* be interpreted as CI in statistics.

Finally, what do you think about renaming `TemporalPoint` to `TemporalPosition` and `TemporalRange` to `TemporalInterval`?

**Comment by pnrobinson** [comment]
Both TemporalPoint and TemporalPosition do not really convey what the class does. What about PointInTime and TimeInterval?

**Comment by ielis** [comment]
Hi @pnrobinson @julesjacobsen I'll merge this PR, I think temporal components are solid.

**Pull request merged**
