### PR TITLE
moving to obg-reader

### PR DESCRIPTION
**Pull request by iimpulse**

### CODE REVIEW

**Review by pnrobinson — APPROVED** [review]
+1

**Review by ielis — CHANGES_REQUESTED** [review]
@iimpulse,

thanks a lot for the PR! I think using `OgJsonReader` will solve the I/O issues.

However, I would like to make sure that we are indeed fixing the issue - right now our tests pass even if we load graph document using the old (now deprecated) `OboGraphDocumentLoader`.

I updated the `hp.module.json` file that we use for testing, to the latest HPO `v2024-06-25`. I would like to further "doctor" one or more nodes to make them look like nodes from the future release and make the current tests fail.
Afterwards, using `OgJsonReader` should fix the failures.

@iimpulse Can you please point me to an example node that has the additional field, or doctor the `hp.module.json` yourself?

**Review by matentzn — COMMENTED** [review]
Awwwwesome!!! I didnt realise the Problem _could_ be fixed here. Before I create another round of churn then:

I was going to publish a release with the old serialiser. I will hold of on that until @ielis tells me otherwise. Please let me know asap if I can use the _new serialiser_ (the one that caused the issue), or wether I should use the old one.

**Comment by ielis** [comment]
Hi @iimpulse @pnrobinson 

## Summary

After a troubleshooting session with @matentzn we believe that the issue manifests when using `obographs<=0.3.0`. Therefore, the most recent HPO releases should work OK as long as `phenol>=1.0.4` is used. 

Seeing
```
Unrecognized field "propertyType" (class org.geneontology.obographs.core.model.Node$Json), not marked as ignorable (4 known properties: "type", "id", "meta", "lbl"])
```
in an app that uses `phenol>=1.0.4` is can be due to a project setup. I'd be happy to troubleshoot these issues, please let me know!

## Details

Now let me describe what we did.

Nico sent me an HPO JSON that contains several nodes with `propertyType` field that was introduced by https://github.com/geneontology/obographs/issues/65
Here is an example of one such node:
```json
{
  "id" : "http://purl.obolibrary.org/obo/HP_0034334",
  "lbl" : "allelic_requirement",
  "type" : "PROPERTY",
  "propertyType" : "ANNOTATION",
  "meta" : {
    "basicPropertyValues" : [ {
      "pred" : "http://purl.org/dc/elements/1.1/date",
      "val" : "2022-09-04T11:14:13Z"
    }, {
      "pred" : "http://purl.org/dc/terms/creator",
      "val" : "https://orcid.org/0000-0002-0736-9199"
    } ]
  }
}
```

The JSON file, however, loaded fine, even without using obograph's `OgJsonReader` class. 

Then we used `obographs==0.3.0` to load the file, and we got the error. While being on `0.3.0`, we used `OgJsonReader` instead of Phenol's `OboGraphDocumentLoader` to no avail.

Therefore, using the latest `obographs` should prevent seeing the error and using `OgJsonReader` will _not_ help with the error.

The fact that `0.3.0 -> 0.3.1` is a breaking change is a bit unfortunate. However, it is "legal", since `obographs` are still in [initial development](https://semver.org/#spec-item-4), according to SemVer.

## What's next

I would like to use `OgJsonReader` nevertheless, since thanks to its usage there will be one less class to maintain in Phenol.. :smirk_cat: 
I also added the above node to the test HPO file to include the parsing in our test suite.
Nevertheless, the outcome will be basically what @iimpulse did at the beginning.

Please let me know your thoughts. Thanks! :slightly_smiling_face:

**Review by ielis — APPROVED** [review]

**Pull request merged**
