### PR TITLE
mim2geneMedgen parser in separate class

### PR DESCRIPTION
**Pull request by pnrobinson**
I would like to disentangle some of the classes in the package with ``Gene2DiseaseAssociationParser``, it is difficult to understand what is going on and probably better to use more of a dependency injection style rather than passing paths to 4 resources and doing everything inside the class.
I added something for  mim2geneMedgen, still need to add tests.

### CODE REVIEW

**Review by iimpulse — APPROVED** [review]

**Comment by pnrobinson** [comment]
I think we still need some work with the HpoAssociationParser -- there are still too many different ways of constructing the class and it is not easly possible to construct with without the Orphanet -- I think it works if we start with File but not with String (path).

**Comment by julesjacobsen** [comment]
This isn't a completely trivial thing to sort out - I implemented this in Exomiser like so:

https://github.com/exomiser/Exomiser/blob/development/exomiser-data-phenotype/src/main/java/org/monarchinitiative/exomiser/data/phenotype/processors/steps/disease/DiseaseGeneStep.java

Essentially due to the way Orphanet produces their files they need to be parsed first, then combined and joined with the OMIM data which has a much more natural fit for the way we need the data. The OMIM geneMap2 file was really useful in this regard as it takes a gene-centric view of the data and also includes the MOI in the file,

**Comment by pnrobinson** [comment]
@julesjacobsen 's suggestion  is partially implemented in the class ``Gene2DiseaseAssociationParser``.

**Comment by pnrobinson** [comment]
I will merge this branch now to simplify downstream development. See https://github.com/monarch-initiative/phenol/issues/307 we still need to implement this.

**Pull request merged**
