### PR TITLE
Uberon map

### PR DESCRIPTION
**Pull request by pnrobinson**
This PR adds mappings between uberon and cell ontology terms that can be used to analyze experimental data such as the FANTOM5 enhancer collection.

### CODE REVIEW

**Review by matentzn — COMMENTED** [review]
Interesting project; I am not a one to review the contents, but here some thoughts on representation.

I extracted all 92 mappings in the pull request into an external mapping file and compared it to the EQ definitions we have in HP at the minute. 

I found that about 1/3 of the chosen entities (31) in the mapping correspond exactly to the EQs, while 39 mappings in this pull request correspond to different entities the EQs. 22 mappings in this pull request have no corresponding EQ to compare to.

I would like to suggest the following: I think that mappings of this kind can be valuable beyond phenol. If we represented mappings consistently in SSSOM tsvs outside the code, people can always choose to reuse them, or change them if they disagree or want to add. It would also be easier to review them by non-coders. Now with 92 mappings in this pull request, I understand that these do not seem worth it - but I do think as a principle, they would be. Not only are these mappings are valuable beyond phenol and tspec - IMO, they belong directly in HPO, or, if you want these mappings to be more controlled as part of your project directly as part of the tspec or whatever repo - they can also give us some interesting feedback into the construction of our EQs (if more than a third of your mappings are not matched in some way by the EQs, this could be interesting).

I understand that you might feel that the mappings here and our EQs somehow say different things - that is no problem! This just means we qualify the mappings with different relations!

 Its nothing important, but here are the three lines of analysis code, and the mapping table if you want it:
https://github.com/matentzn/phenol_mappings

**Comment by pnrobinson** [comment]
@matentzn  what is SSSOM -- it looks like this is a simple TSV file with a fancy name haha.
But I take your point that we do not want to hard code this.
It seems it is better to put the default mappings in the resources bundle but to provide a class that can optionally take another similarly formated file. For downstream use, I need the labels of the terms and it would be unnice to require that the entire CL and uberon be parsed for that. Therefore, I think the better format is this
```
Other.Ontology.id -- Other.Ontology.label  -- HPO.id  --  HPO.label 
```
and to have some comment lines with versions.

**Comment by matentzn** [comment]
Would it be a problem if you used the sssom header names instead?

like https://github.com/matentzn/phenol_mappings/blob/master/phenol_uberon_map_sssom.tsv, just with two columns for label (subject_label, object_label)!

I just want to try and standardise these kinds of tables everywhere :) Or are you totally against that?

**Comment by pnrobinson** [comment]
what is the column name for label? And what is the relation for Peter thinks they are kinda similar? :-0. 
This is a more or less experimental feature, but I think that other people would appreciate having it in the library.

**Comment by pnrobinson** [comment]
So this is what I need
```
#HPO-Uberon/CL map,,,
#version: 2020-11-18,,,
id,label,hpo.id,hpo.label
CL:0000622,acinar cell,HP:0000818,Abnormality of the endocrine system
CL:0002536,epithelial cell of amnion,HP:0001197,Abnormality of prenatal development or birth
(...)
```

**Comment by pnrobinson** [comment]
@matentzn  I will merge this now, it will simplify work on a client program. We can return to this before the next maven release.

**Pull request merged**
