### PR TITLE
Replaced the internal graph codes with JGraphT

### PR DESCRIPTION
**Pull request by yy20716**
Hello, the branch in this pull request contains the whole new phenol that uses JGraphT as a back-end graph library. 
  - I removed existing graph codes and added some wrappers/utility classes to maintain compatibility of codes. 
  - I revised test cases based on the JGraphT and added comments to explain changes in codes.

Additionally, I made the following changes:
  - I reformatted codes using Google's Java-style because many codes were written based on different formats.
  - I resolved all warnings such as missing types.
  - I refactored codes based on the suggestions in this [post](https://github.com/monarch-initiative/phenol/issues/39), i.e. `TermRelation` and `RelationQualifier` in the old phenol are now changed into `Relationship` and `RelationshipType`, respectively. Subclass hierarchies are also added for these classes to remove redundancies as well.
  - I added me as the author of codes in comments and readme.MD (Hopefully you don't mind).

I confirmed all existing testcases were passed without issues, but I would greatly appreciate it if someone could pull this branch and run testcases to double-check every case works as intended (i.e. by running `mvn clean install`), before merging this into the `develop` branch. Please let us know if you encounter any issues. Thank you for your time.

### CODE REVIEW

**Comment by pnrobinson** [comment]
I just did a $mvn clean test in this branch and got
```
Reactor Summary:
[INFO] 
[INFO] org.monarchinitiative.phenol:phenol ................ SUCCESS [  2.734 s]
[INFO] org.monarchinitiative.phenol:phenol-core ........... SUCCESS [ 12.410 s]
[INFO] org.monarchinitiative.phenol:phenol-io ............. SUCCESS [ 13.492 s]
[INFO] org.monarchinitiative.phenol:phenol-cli ............ SUCCESS [  0.398 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------
```

**Comment by yy20716** [comment]
Thank you for your quick confirmation. Yes, I guess there might be some (potential) glitches that I missed. Please let us know if you find out any issues.

**Comment by yy20716** [comment]
Oh sorry I just saw this post (I was a bit distracted due to the lunch). Let me test your ones. Thanks.

**Comment by yy20716** [comment]
**Short version**: Peter, I tested your `hpoannotqc` but I failed to reproduce your issue on my and other people's linux machines. If you don't mind, could you please remove your `.m2` directory (a local repo for maven) and test your codes one more time again? I guess `phenol` is not properly updated in your local repository.

**Long version**: 
 - I was trying to compile and run the master branch of your `hpoannotqc`. It seemed that the command in your previous post (`$ java -jar target/HpoAnnotQc.jar -a dummy -h /path/to/hp.obo`) did not have a required command mode/parameter, i.e. it showed the message that I should run with one of the three parameters such as `download`, `convert`, and `big-file`. 
 - I was not sure which mode I should run first, but running `download` mode might be the choice. The program downloaded some files including `hp.obo` in `data` directory. However, I was still not able to run "convert" still; it was looking for RD annotation files but I was not sure where to get them.
 - As a workaround, I revised the `BigFileWriterTest` to include an additional testcase that loads `hp.obo` as follows.

~~~~
        try {
            HpoOboParser hpoOboParser = new HpoOboParser(new File("data/hp.obo"));
            HpoOntology ontology = hpoOboParser.parse();
            System.out.println("edge#: " + ontology.getGraph().edgeSet().size());
        } catch (IOException e) {
            return;
        }
~~~~

 - I ran the testcase and the ontology was loaded as expected, i.e. it did not stop while executing "parse()", and I was able to see the number of the edge (`edge#: 17162`) in the end. 
 - So my speculation is that "hpoOboParser.parse()" might be okay but `phenol` in your local repository/the hp.obo file might be old ones that require updates. Could you please remove ".m2", rebuild phenol (using the `replace-with-JgraphT` branch) and `HpoAnnotQc`, and then re-run your codes one more time again? I guess then it would work. Thank you for your time.

**Comment by yy20716** [comment]
ok, I also ran MergerTest.java and found that this one was stuck while parsing the file as you pointed out. It seems it uses the different hp.obo file. I will check one more time. Thanks.

**Comment by yy20716** [comment]
ok, I am going through testcases in `hpoannotqc/src/test/java/org/monarchinitiative/hpoannotqc/smallfile`, e.g., UpdateLabelTest. I confirmed that loading the ontology itself (hp.obo) is fine, i.e. it takes some time but finishes, but the execution is stuck while running codes in Phenol's OntologyAlgorithm. I wonder whether I may break up some logics there mistakenly but will continue checking. I will upload the hotfix into this branch if I found the problem. Thanks.

**Comment by yy20716** [comment]
Peter, I am wondering whether the issues related to hpoannotqc existed even before I replaced the graph codes with JGraphT.  

 - I am observing that the testcases in hpoannotqc are running forever. I initially thought there might be some issues on loading ontologies as you suggested but it seems that we do not have issues so far. However, I see a bug from the testcase. Specifically, this bug happens when smallfile's [UpdateLabelTest](https://github.com/monarch-initiative/hpoannotqc/blob/master/src/test/java/org/monarchinitiative/hpoannotqc/smallfile/UpdateLabelTest.java) is executed. In this test, the execution is stuck at [this point](https://github.com/monarch-initiative/hpoannotqc/blob/2dea9e78fd0409d14d08db5793558b7e433f1307/src/test/java/org/monarchinitiative/hpoannotqc/smallfile/UpdateLabelTest.java#L46).  What it does is to find ModifierTerms using [this method](https://github.com/monarch-initiative/hpoannotqc/blob/2dea9e78fd0409d14d08db5793558b7e433f1307/src/main/java/org/monarchinitiative/hpoannotqc/smallfile/OldSmallFileEntry.java#L176) and as you can see, this one calls [getChildren(TermId parent)](https://github.com/monarch-initiative/hpoannotqc/blob/2dea9e78fd0409d14d08db5793558b7e433f1307/src/main/java/org/monarchinitiative/hpoannotqc/smallfile/OldSmallFileEntry.java#L193). I guess the commented codes were the one what you probably wrote first, which simply retrieves direct childrens of the node given. It seems that you later revised this method to call [getChildren() from OntologyAlgorithm in phenol](https://github.com/monarch-initiative/phenol/blob/4ce25184e3cc15b9043ad92bd45c736e869fabaf/phenol-core/src/main/java/org/monarchinitiative/phenol/ontology/algo/OntologyAlgorithm.java#L54) but that method additionally retrieves the parent (or the given node) itself. Therefore, it iterates the parent node forever. 

  - I believe that we could fix this issue if we could call [this method](https://github.com/monarch-initiative/phenol/blob/4ce25184e3cc15b9043ad92bd45c736e869fabaf/phenol-core/src/main/java/org/monarchinitiative/phenol/ontology/algo/OntologyAlgorithm.java#L65) instead, after we set the parameter `includeOriginalTerm` as false.

  - It is also possible that this is a completely different issue; if you found any other issues from phenol, please let me know. I see other tests are also broken but didn't have chances to look at them. Thank you for reading this long post.

**Comment by pnrobinson** [comment]
Thank very very much for this! Your diagnosis is correct, it was the call to getParents in the loop that started an infinite recursion. I replaced the method with 
```
Set<TermId> descendents = getDescendents(ontology,modifier);
```
and now that problem was fixed and HpoAnnotQc is working again. 
I will continue testing today and merge the branch a little later, but it is looking good. Thank you!

**Comment by pnrobinson** [comment]
I would also add all of the new items to the change log and up the version number, OK?

**Comment by yy20716** [comment]
Thank you for your quick confirmation. Yes, I would appreciate it if you could update the changelog and the version number. Please let us know if you find out any other issues. Thank you.

**Pull request merged**
